name: Capture Screenshot and Audio

on: [push]

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb firefox pulseaudio ffmpeg imagemagick

      - name: Run capture script
        run: |
          chmod +x ./capture.sh
          ./capture.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: capture-output
          path: |
            screenshot.png
            output.mp4
